# Generated by Django 5.2.17 on 2026-09-01 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('reg_no', models.CharField(max_length=9)),
                ('section', models.CharField(max_length=1)),
                ('mobile', models.IntegerField(max_length=10)),
            ],
        ),
    ]
