# Generated by Django 5.2.17 on 2026-09-01 06:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='mobile',
            field=models.CharField(verbose_name=django.core.validators.RegexValidator(message='please enter a valid phone number', regex='^[6-9]\\d{9}$')),
        ),
    ]
